// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH_cLVgwZc9QBLM7xt7vtrvTPQqQcuVBI',
    appId: '1:931182773293:web:5d27dc3fcb32f5e6a1a4a4',
    messagingSenderId: '931182773293',
    projectId: 'temperature-2f7f0',
    authDomain: 'temperature-2f7f0.firebaseapp.com',
    databaseURL: 'https://temperature-2f7f0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'temperature-2f7f0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCneFevXYVPxfk9tX7JBNiVvLEGqsBmV6w',
    appId: '1:931182773293:android:aa3297d2991305d6a1a4a4',
    messagingSenderId: '931182773293',
    projectId: 'temperature-2f7f0',
    databaseURL: 'https://temperature-2f7f0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'temperature-2f7f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd0SwXQev1s0I6S45k_jJIYMiy4rx2Ybc',
    appId: '1:931182773293:ios:50bcbede6b4ecb63a1a4a4',
    messagingSenderId: '931182773293',
    projectId: 'temperature-2f7f0',
    databaseURL: 'https://temperature-2f7f0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'temperature-2f7f0.appspot.com',
    iosClientId: '931182773293-q716v8e2f0p7qtla1tpupb55t1hebjm0.apps.googleusercontent.com',
    iosBundleId: 'com.example.madLab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd0SwXQev1s0I6S45k_jJIYMiy4rx2Ybc',
    appId: '1:931182773293:ios:50bcbede6b4ecb63a1a4a4',
    messagingSenderId: '931182773293',
    projectId: 'temperature-2f7f0',
    databaseURL: 'https://temperature-2f7f0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'temperature-2f7f0.appspot.com',
    iosClientId: '931182773293-q716v8e2f0p7qtla1tpupb55t1hebjm0.apps.googleusercontent.com',
    iosBundleId: 'com.example.madLab',
  );
}
